#![cfg(feature = "assets")]

//! Phase 1 behavior for the headless asset service: rooting, admission,
//! identity, bounded staged processing, decoding, eviction and teardown.
//!
//! Small fixtures and their expected RGBA8 bytes are committed under
//! `tests/fixtures/assets` and regenerated by `tools/asset_fixtures.py`, which
//! specifies both the PNG framing and the pixels independently of this engine.
//! The large fixtures are built here from stored DEFLATE blocks for the same
//! reason: no encoder shared with the decoder under test participates.

use protogine::assets::{
    AssetErrorCode, AssetStore, DIMENSION_LIMIT, ENCODED_IMAGE_LIMIT, ENCODED_STAGING_LIMIT,
    GpuResidency, IMAGE_REGISTRY_LIMIT, IMAGE_RGBA_LIMIT, ImageId, ImageState, ImageStatus,
    JOB_QUEUE_LIMIT, LoadStage, QUANTA_PER_PASS, SPELLING_MEMO_LIMIT, STORE_RGBA_LIMIT,
    WORK_QUANTUM,
};
use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    process::Command,
    sync::Mutex,
    thread,
    time::{Duration, Instant},
};

const WATCHDOG: Duration = Duration::from_secs(10);

/// Source paths are absolute so that the working-directory test below cannot
/// disturb tests running beside it.
fn source(relative: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn fixture(name: &str) -> PathBuf {
    source(&format!("tests/fixtures/assets/{name}"))
}

fn kenney() -> PathBuf {
    source("examples/kenney_1-bit-pack_transparent-packed.png")
}

/// Tests that repoint the process working directory serialize against each
/// other. Every other test addresses absolute paths only.
static WORKING_DIRECTORY: Mutex<()> = Mutex::new(());

fn bundle() -> tempfile::TempDir {
    tempfile::tempdir().expect("temporary bundle")
}

fn install(root: &Path, name: &str, relative: &str) {
    let destination = root.join(relative);
    fs::create_dir_all(destination.parent().expect("relative path has a parent")).unwrap();
    fs::copy(fixture(&format!("{name}.png")), destination).unwrap();
}

fn expected(name: &str) -> Vec<u8> {
    fs::read(fixture(&format!("{name}.rgba"))).unwrap()
}

fn store(root: &Path) -> AssetStore {
    AssetStore::new(root).expect("asset store")
}

/// Load one image to completion and return its published pixels.
fn load(store: &mut AssetStore, path: &str) -> Vec<u8> {
    let id = store.request_png(path).unwrap();
    assert!(store.drain(WATCHDOG), "{path} did not settle");
    let status = store.status(id).unwrap();
    assert_eq!(status.state, ImageState::Ready, "{path}: {status:?}");
    store.image(id).unwrap().rgba().to_vec()
}

/// Independent PNG framing: fixed CRC and Adler tables, stored DEFLATE blocks,
/// and no dependency on the decoder or on any encoder in this workspace.
mod png {
    pub const SIGNATURE: &[u8] = b"\x89PNG\r\n\x1a\n";

    fn crc32(bytes: &[u8]) -> u32 {
        let mut crc = u32::MAX;
        for byte in bytes {
            crc ^= u32::from(*byte);
            for _ in 0..8 {
                crc = (crc >> 1) ^ (0xedb8_8320 & 0u32.wrapping_sub(crc & 1));
            }
        }
        !crc
    }

    pub fn chunk(out: &mut Vec<u8>, kind: &[u8; 4], data: &[u8]) {
        out.extend_from_slice(&(data.len() as u32).to_be_bytes());
        let mut framed = kind.to_vec();
        framed.extend_from_slice(data);
        out.extend_from_slice(&framed);
        out.extend_from_slice(&crc32(&framed).to_be_bytes());
    }

    /// zlib framing with stored (uncompressed) blocks, so the encoded size of a
    /// fixture is predictable to the byte.
    pub fn zlib_stored(raw: &[u8]) -> Vec<u8> {
        let mut out = vec![0x78, 0x01];
        let (mut a, mut b) = (1u32, 0u32);
        for (index, block) in raw.chunks(65535).enumerate() {
            out.push(u8::from((index + 1) * 65535 >= raw.len()));
            let length = block.len() as u16;
            out.extend_from_slice(&length.to_le_bytes());
            out.extend_from_slice(&(!length).to_le_bytes());
            out.extend_from_slice(block);
            for byte in block {
                a = (a + u32::from(*byte)) % 65521;
                b = (b + a) % 65521;
            }
        }
        out.extend_from_slice(&((b << 16) | a).to_be_bytes());
        out
    }

    /// A non-interlaced RGBA8 PNG with filter 0 on every scanline.
    pub fn rgba(pixels: &[u8], width: usize, height: usize) -> Vec<u8> {
        assert_eq!(pixels.len(), width * height * 4);
        let mut raw = Vec::with_capacity(height * (1 + width * 4));
        for row in pixels.chunks_exact(width * 4) {
            raw.push(0);
            raw.extend_from_slice(row);
        }
        let mut out = SIGNATURE.to_vec();
        let mut header = Vec::new();
        header.extend_from_slice(&(width as u32).to_be_bytes());
        header.extend_from_slice(&(height as u32).to_be_bytes());
        header.extend_from_slice(&[8, 6, 0, 0, 0]);
        chunk(&mut out, b"IHDR", &header);
        chunk(&mut out, b"IDAT", &zlib_stored(&raw));
        chunk(&mut out, b"IEND", &[]);
        out
    }

    /// The Phase 0 xorshift64 sequence, so encoded sizes stay comparable.
    pub fn noise(width: usize, height: usize) -> Vec<u8> {
        let mut state = 0x0123_4567_89ab_cdef_u64;
        (0..width * height * 4)
            .map(|_| {
                state ^= state << 13;
                state ^= state >> 7;
                state ^= state << 17;
                state as u8
            })
            .collect()
    }
}

// ---- decoding ----------------------------------------------------------

#[test]
fn committed_fixtures_decode_to_independently_specified_pixels() {
    for (fixture, width, height) in [
        ("gray", 2, 1),
        ("gray_alpha", 2, 1),
        ("rgb", 3, 1),
        ("rgba", 2, 3),
        ("palette", 2, 1),
        ("interlaced", 9, 9),
    ] {
        let root = bundle();
        install(root.path(), fixture, "art/image.png");
        let mut store = store(root.path());
        let id = store.request_png("art/image.png").unwrap();
        assert_eq!(store.status(id).unwrap().state, ImageState::Queued);
        assert!(store.drain(WATCHDOG), "{fixture} did not settle");

        let image = store
            .image(id)
            .unwrap_or_else(|| panic!("{fixture} not ready"));
        assert_eq!(
            (image.width(), image.height()),
            (width, height),
            "{fixture}"
        );
        assert_eq!(image.rgba(), expected(fixture), "{fixture}");
        assert_eq!(
            image.rgba().len(),
            (width * height * 4) as usize,
            "{fixture}"
        );
        assert_eq!(store.size(id), Some((width, height)), "{fixture}");

        let status = store.status(id).unwrap();
        assert_eq!(status.state, ImageState::Ready, "{fixture}");
        assert_eq!(status.stage, LoadStage::Complete, "{fixture}");
        assert_eq!(status.error, None, "{fixture}");
        // No graphics context is attached to a headless store.
        assert_eq!(status.gpu, GpuResidency::Unavailable, "{fixture}");
        assert_eq!(status.bytes_read, image.encoded_bytes(), "{fixture}");
        // Encoded staging and decoder workspace are released on completion;
        // only the retained RGBA output survives.
        assert_eq!(store.staged_bytes(), 0, "{fixture}");
        assert_eq!(store.scratch_bytes(), 0, "{fixture}");
        assert_eq!(store.resident_bytes(), image.rgba().len(), "{fixture}");
        assert!(store.service_fault().is_none(), "{fixture}");
    }
}

#[test]
fn malformed_and_unsupported_images_become_inspectable_failed_jobs() {
    for (fixture, code) in [
        ("sixteen_bit", AssetErrorCode::Unsupported),
        ("apng", AssetErrorCode::Unsupported),
        ("huge_dimensions", AssetErrorCode::Limit),
        ("truncated", AssetErrorCode::Format),
        ("corrupt", AssetErrorCode::Format),
        ("wrong_format", AssetErrorCode::Format),
    ] {
        let root = bundle();
        install(root.path(), fixture, "art.png");
        let mut store = store(root.path());
        // Admission succeeds: content failures are inspectable, not catchable
        // refusals, and they publish a handle first.
        let id = store.request_png("art.png").unwrap();
        assert!(store.drain(WATCHDOG), "{fixture} did not settle");

        let status = store.status(id).unwrap();
        assert_eq!(status.state, ImageState::Failed, "{fixture}");
        let error = status.error.as_ref().unwrap_or_else(|| panic!("{fixture}"));
        assert_eq!(error.code, code, "{fixture}: {error}");
        assert_eq!(error.path, "art.png", "{fixture}");
        assert!(!error.message.is_empty(), "{fixture}");
        assert!(store.image(id).is_none(), "{fixture}");
        assert_eq!(store.size(id), None, "{fixture}");
        // A failed job is not a service fault and stops no gameplay.
        assert!(store.service_fault().is_none(), "{fixture}");
        assert_eq!(store.staged_bytes(), 0, "{fixture}");
        assert_eq!(store.scratch_bytes(), 0, "{fixture}");
        assert_eq!(store.resident_bytes(), 0, "{fixture}");
        assert_eq!(store.pending_jobs(), 0, "{fixture}");

        // The failure left the path lookup, so an explicit retry is a new image.
        let retry = store.request_png("art.png").unwrap();
        assert_ne!(retry, id, "{fixture}");
        assert!(retry.number() > id.number(), "{fixture}");
    }
}

#[test]
fn a_dimension_over_the_bound_is_refused_before_any_output_allocation() {
    let root = bundle();
    let width = DIMENSION_LIMIT as usize + 1;
    fs::write(
        root.path().join("wide.png"),
        png::rgba(&vec![7; width * 4], width, 1),
    )
    .unwrap();
    let mut store = store(root.path());
    let id = store.request_png("wide.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let status = store.status(id).unwrap();
    assert_eq!(status.state, ImageState::Failed);
    assert_eq!(status.error.unwrap().code, AssetErrorCode::Limit);
    assert_eq!(store.resident_bytes(), 0);
    // The largest accepted image is exactly the bound in both directions.
    assert_eq!(
        (DIMENSION_LIMIT as usize) * (DIMENSION_LIMIT as usize) * 4,
        IMAGE_RGBA_LIMIT
    );
}

// ---- rooting -----------------------------------------------------------

#[test]
fn requests_resolve_against_the_bundle_root_not_the_working_directory() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let elsewhere = bundle();
    // A different image at exactly the same relative path in an unrelated cwd.
    fs::create_dir_all(elsewhere.path().join("art")).unwrap();
    fs::copy(fixture("rgb.png"), elsewhere.path().join("art/tiles.png")).unwrap();
    let bundle_pixels = expected("rgba");
    let decoy_pixels = expected("rgb");

    let guard = WORKING_DIRECTORY.lock().unwrap_or_else(|e| e.into_inner());
    let previous = std::env::current_dir().unwrap();
    std::env::set_current_dir(elsewhere.path()).unwrap();
    let mut store = AssetStore::new(root.path()).unwrap();
    let pixels = load(&mut store, "art/tiles.png");
    std::env::set_current_dir(&previous).unwrap();
    drop(guard);

    assert_eq!(pixels, bundle_pixels);
    assert_ne!(pixels, decoy_pixels);
}

#[test]
fn valid_names_may_nest_and_carry_spaces_or_unicode() {
    let root = bundle();
    for relative in [
        "tiles.png",
        "art/tiles.png",
        "art/rooms/deep/tiles.png",
        "art/my room/tiles.png",
        "art/\u{5730}\u{56f3}.png",
        "art/tiles.PNG",
        "art/tiles.PnG",
    ] {
        install(root.path(), "rgba", relative);
        let mut store = store(root.path());
        assert_eq!(load(&mut store, relative), expected("rgba"), "{relative}");
    }
}

#[test]
fn the_request_path_policy_refuses_unportable_and_escaping_spellings() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    for path in [
        "",
        "..",
        "../tiles.png",
        "art/../tiles.png",
        "art/./tiles.png",
        "art//tiles.png",
        "/art/tiles.png",
        "art/tiles.png/",
        "C:/art/tiles.png",
        "\\\\server\\share\\tiles.png",
        "art\\tiles.png",
        "NUL.png",
        "com1.png",
        "art/tiles.png ",
        "art/tiles.png.",
        "art/tiles.jpg",
        "tiles",
        ".png.jpg",
        "art/til\u{7}es.png",
    ] {
        let error = store.request_png(path).unwrap_err();
        assert_eq!(error.code, AssetErrorCode::Path, "{path:?}: {error}");
    }
    let long = format!("{}.png", "a".repeat(5000));
    assert_eq!(
        store.request_png(&long).unwrap_err().code,
        AssetErrorCode::Path
    );
    assert_eq!(store.counters().admitted, 0);
    assert_eq!(store.counters().refused, 20);
    assert_eq!(store.pending_jobs(), 0);
}

#[test]
fn missing_files_and_non_regular_nodes_are_refused_before_admission() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    fs::create_dir(root.path().join("folder.png")).unwrap();
    let mut store = store(root.path());
    assert_eq!(
        store.request_png("art/missing.png").unwrap_err().code,
        AssetErrorCode::Io
    );
    assert_eq!(
        store.request_png("missing/tiles.png").unwrap_err().code,
        AssetErrorCode::Io
    );
    // A directory that merely looks like an image is not a regular file.
    assert_eq!(
        store.request_png("folder.png").unwrap_err().code,
        AssetErrorCode::Path
    );
    // A file cannot be an intermediate directory.
    assert_eq!(
        store
            .request_png("art/tiles.png/inner.png")
            .unwrap_err()
            .code,
        AssetErrorCode::Path
    );
    assert_eq!(store.counters().admitted, 0);
}

/// Directory junctions need no Windows privilege, so this boundary is always
/// covered here. File symlinks additionally require SeCreateSymbolicLink (or
/// Developer Mode) and are therefore not created by this suite; the traversal
/// rejects both through the same reparse-point check.
#[cfg(windows)]
#[test]
fn reparse_points_below_the_root_are_refused() {
    let root = bundle();
    let outside = bundle();
    fs::copy(fixture("rgba.png"), outside.path().join("tiles.png")).unwrap();
    let junction = root.path().join("art");
    let script = "New-Item -ItemType Junction -Path $env:PROTOGINE_LINK -Target $env:PROTOGINE_LINK_TARGET | Out-Null";
    let status = std::process::Command::new("powershell.exe")
        .args(["-NoProfile", "-Command", script])
        .env("PROTOGINE_LINK", &junction)
        .env("PROTOGINE_LINK_TARGET", outside.path())
        .status()
        .unwrap();
    assert!(status.success(), "junction fixture could not be created");

    let mut store = store(root.path());
    let refused = store.request_png("art/tiles.png");
    fs::remove_dir(&junction).unwrap();
    let error = refused.unwrap_err();
    assert_eq!(error.code, AssetErrorCode::Path, "{error}");
    assert!(
        error.message.contains("symlinks and reparse points"),
        "{error}"
    );
    assert!(outside.path().join("tiles.png").exists());
}

/// Case-insensitive platforms canonicalize both spellings to one file, so the
/// image is reused rather than decoded twice. Case-sensitive filesystems keep
/// them distinct, which is why nothing is globally lowercased.
#[cfg(windows)]
#[test]
fn platform_case_aliases_reuse_one_image() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    let first = store.request_png("art/tiles.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let before = store.counters();
    let second = store.request_png("ART/Tiles.PNG").unwrap();
    assert_eq!(first, second);
    let after = store.counters();
    assert_eq!(after.admitted, before.admitted);
    assert_eq!(after.coalesced, before.coalesced + 1);
    assert_eq!(after.bytes_read, before.bytes_read);
}

// ---- identity, coalescing and caches -----------------------------------

#[test]
fn pending_requests_for_one_path_coalesce_onto_one_job() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    let first = store.request_png("art/tiles.png").unwrap();
    let second = store.request_png("art/tiles.png").unwrap();
    assert_eq!(first, second);
    assert_eq!(store.pending_jobs(), 1);
    assert_eq!(store.counters().admitted, 1);
    assert_eq!(store.counters().spelling_hits, 1);
    assert!(store.drain(WATCHDOG));
    assert_eq!(store.counters().completed, 1);
}

#[test]
fn a_ready_image_is_never_read_or_decoded_again() {
    let root = bundle();
    install(root.path(), "interlaced", "art/tiles.png");
    let mut store = store(root.path());
    let id = store.request_png("art/tiles.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let settled = store.take_settled();
    assert_eq!(settled.len(), 1);
    assert_eq!(settled[0].state, ImageState::Ready);

    let before = store.counters();
    for _ in 0..32 {
        assert_eq!(store.request_png("art/tiles.png").unwrap(), id);
        assert_eq!(store.status(id).unwrap().state, ImageState::Ready);
        assert_eq!(store.size(id), Some((9, 9)));
        assert!(store.image(id).is_some());
        store.service();
    }
    let after = store.counters();
    assert_eq!(after.bytes_read, before.bytes_read);
    assert_eq!(after.read_calls, before.read_calls);
    assert_eq!(after.decode_bands, before.decode_bands);
    assert_eq!(after.completed, before.completed);
    assert_eq!(after.admitted, before.admitted);
    assert_eq!(after.spelling_hits, before.spelling_hits + 32);
    assert!(store.take_settled().is_empty());
}

#[test]
fn the_spelling_memo_holds_only_live_images() {
    let root = bundle();
    for index in 0..4 {
        install(root.path(), "rgba", &format!("art/{index}.png"));
    }
    let mut store = store(root.path());
    let ids: Vec<_> = (0..4)
        .map(|index| store.request_png(&format!("art/{index}.png")).unwrap())
        .collect();
    assert!(store.drain(WATCHDOG));
    assert_eq!(store.memoized_spellings(), 4);

    // Eviction removes the spelling with its image, so a later request cannot
    // be answered from a memo entry naming a dead identity.
    assert!(store.unload(ids[1]));
    assert_eq!(store.memoized_spellings(), 3);
    let replacement = store.request_png("art/1.png").unwrap();
    assert_ne!(replacement, ids[1]);
    assert_eq!(store.memoized_spellings(), 4);
    // The other images are untouched by their neighbour's eviction.
    for id in [ids[0], ids[2], ids[3]] {
        assert_eq!(store.status(id).unwrap().state, ImageState::Ready);
    }
}

/// A live image can hold more spellings than the registry holds images only
/// where the platform accepts aliases, which is why the memo has its own bound.
/// Case-sensitive filesystems reach it no other way, and nothing is lowercased
/// to manufacture aliases there.
#[cfg(windows)]
#[test]
fn the_spelling_memo_is_bounded_and_dropping_it_never_unloads_an_image() {
    fn case_variant(path: &str, mask: u32) -> String {
        let mut bit = 0;
        path.chars()
            .map(|letter| {
                if !letter.is_ascii_alphabetic() {
                    return letter;
                }
                let upper = (mask >> bit) & 1 == 1;
                bit += 1;
                if upper {
                    letter.to_ascii_uppercase()
                } else {
                    letter.to_ascii_lowercase()
                }
            })
            .collect()
    }

    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    let kept = store.request_png("art/tiles.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let bytes_read = store.counters().bytes_read;

    let spellings = SPELLING_MEMO_LIMIT + 44;
    for mask in 0..spellings as u32 {
        let spelling = case_variant("art/tiles.png", mask);
        assert_eq!(store.request_png(&spelling).unwrap(), kept, "{spelling}");
    }
    assert_eq!(store.memoized_spellings(), SPELLING_MEMO_LIMIT);

    // The earliest spellings were replaced, but the image is untouched: the
    // canonical path lookup still coalesces onto the same identity, and no
    // file was reopened to decide that.
    let before = store.counters();
    assert_eq!(store.status(kept).unwrap().state, ImageState::Ready);
    assert_eq!(store.request_png("art/tiles.png").unwrap(), kept);
    let after = store.counters();
    assert_eq!(after.spelling_hits, before.spelling_hits);
    assert_eq!(after.coalesced, before.coalesced + 1);
    assert_eq!(after.bytes_read, bytes_read);
    assert_eq!(store.image(kept).unwrap().rgba(), expected("rgba"));
}

#[test]
fn identities_are_never_reissued_after_a_rolled_back_publication() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());

    // Rolled back before the worker ever saw it.
    let queued = store.request_png("art/tiles.png").unwrap();
    assert!(store.roll_back(queued));
    assert!(store.status(queued).is_none());
    assert_eq!(store.pending_jobs(), 0);
    assert!(store.take_settled().is_empty());

    // Rolled back while loading.
    let loading = store.request_png("art/tiles.png").unwrap();
    assert!(loading.number() > queued.number());
    store.advance(WATCHDOG);
    store.advance(WATCHDOG);
    assert!(store.roll_back(loading));
    assert!(store.drain(WATCHDOG));
    assert!(store.status(loading).is_none());
    assert!(store.take_settled().is_empty());

    // Rolled back after publication, releasing its storage.
    let ready = store.request_png("art/tiles.png").unwrap();
    assert!(store.drain(WATCHDOG));
    assert!(store.resident_bytes() > 0);
    store.take_settled();
    assert!(store.roll_back(ready));
    store.service();
    assert_eq!(store.resident_bytes(), 0);

    let fresh = store.request_png("art/tiles.png").unwrap();
    for burned in [queued, loading, ready] {
        assert_ne!(fresh, burned);
        assert!(fresh.number() > burned.number());
    }
    assert!(!store.roll_back(queued));
    assert_eq!(store.counters().admitted, 4);
    assert!(store.service_fault().is_none());
}

#[test]
fn identities_from_another_store_are_refused_by_every_operation() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut first = store(root.path());
    let mut second = store(root.path());
    let mine = first.request_png("art/tiles.png").unwrap();
    let theirs = second.request_png("art/tiles.png").unwrap();
    assert!(first.drain(WATCHDOG));
    assert!(second.drain(WATCHDOG));

    // The image numbers deliberately match; only the session separates them.
    assert_eq!(mine.number(), theirs.number());
    assert_ne!(mine.session(), theirs.session());
    assert_ne!(mine, theirs);
    assert!(first.status(theirs).is_none());
    assert_eq!(first.size(theirs), None);
    assert!(first.image(theirs).is_none());
    assert!(!first.unload(theirs));
    assert!(!first.roll_back(theirs));
    assert!(first.status(mine).is_some());
    assert!(first.service_fault().is_none());
}

#[test]
fn a_replaced_file_reloads_in_the_next_session() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let (first_session, first_pixels) = {
        let mut store = store(root.path());
        (store.session(), load(&mut store, "art/tiles.png"))
    };
    install(root.path(), "rgb", "art/tiles.png");
    let mut next = store(root.path());
    assert_ne!(next.session(), first_session);
    assert_eq!(first_pixels, expected("rgba"));
    assert_eq!(load(&mut next, "art/tiles.png"), expected("rgb"));
}

// ---- admission bounds --------------------------------------------------

#[test]
fn admission_refuses_beyond_the_job_queue_bound() {
    let root = bundle();
    for index in 0..=JOB_QUEUE_LIMIT {
        install(root.path(), "rgba", &format!("art/{index}.png"));
    }
    let mut store = store(root.path());
    for index in 0..JOB_QUEUE_LIMIT {
        store.request_png(&format!("art/{index}.png")).unwrap();
    }
    let error = store
        .request_png(&format!("art/{JOB_QUEUE_LIMIT}.png"))
        .unwrap_err();
    assert_eq!(error.code, AssetErrorCode::Limit, "{error}");
    assert_eq!(store.pending_jobs(), JOB_QUEUE_LIMIT);
    assert_eq!(store.counters().admitted, JOB_QUEUE_LIMIT as u64);

    // Draining the queue makes room again without a new store.
    assert!(store.drain(WATCHDOG));
    assert_eq!(store.counters().completed, JOB_QUEUE_LIMIT as u64);
    store
        .request_png(&format!("art/{JOB_QUEUE_LIMIT}.png"))
        .unwrap();
}

#[test]
fn admission_refuses_beyond_the_registry_bound_until_a_slot_is_released() {
    let root = bundle();
    for index in 0..=IMAGE_REGISTRY_LIMIT {
        install(root.path(), "rgba", &format!("art/{index}.png"));
    }
    let mut store = store(root.path());
    let mut resident = Vec::new();
    for index in 0..IMAGE_REGISTRY_LIMIT {
        resident.push(store.request_png(&format!("art/{index}.png")).unwrap());
        if store.pending_jobs() == JOB_QUEUE_LIMIT {
            assert!(store.drain(WATCHDOG));
        }
    }
    assert!(store.drain(WATCHDOG));
    let error = store
        .request_png(&format!("art/{IMAGE_REGISTRY_LIMIT}.png"))
        .unwrap_err();
    assert_eq!(error.code, AssetErrorCode::Limit, "{error}");

    // An unloaded entry keeps its slot until the host drains the transition.
    assert!(store.unload(resident[0]));
    assert!(
        store
            .request_png(&format!("art/{IMAGE_REGISTRY_LIMIT}.png"))
            .is_err()
    );
    store.take_settled();
    store
        .request_png(&format!("art/{IMAGE_REGISTRY_LIMIT}.png"))
        .unwrap();
}

// ---- staged processing -------------------------------------------------

#[test]
fn loading_is_staged_across_bounded_passes_and_yields_identical_pixels() {
    let root = bundle();
    fs::copy(kenney(), root.path().join("sheet.png")).unwrap();
    let reference = {
        let mut store = store(root.path());
        load(&mut store, "sheet.png")
    };
    assert_eq!(reference.len(), 784 * 352 * 4);

    let mut store = store(root.path());
    let id = store.request_png("sheet.png").unwrap();
    let mut previous = store.counters();
    let mut stages = vec![store.status(id).unwrap().stage];
    let mut passes = 0;
    while store.status(id).unwrap().state != ImageState::Ready {
        store.advance(WATCHDOG);
        passes += 1;
        assert!(passes < 200, "loading did not converge");
        let now = store.counters();
        // One pass moves at most the frozen grant, whatever the file size.
        assert!(
            now.bytes_read - previous.bytes_read <= (QUANTA_PER_PASS * WORK_QUANTUM) as u64,
            "pass {passes} read too much"
        );
        assert!(
            now.decode_bands - previous.decode_bands <= QUANTA_PER_PASS as u64,
            "pass {passes} decoded too many bands"
        );
        assert!(store.staged_bytes() <= ENCODED_STAGING_LIMIT);
        previous = now;
        let status = store.status(id).unwrap();
        if stages.last() != Some(&status.stage) {
            stages.push(status.stage);
        }
    }
    // Genuinely staged: the file cannot arrive in a single pass. One pass each
    // for start, read, header, allocate and reader construction, then the
    // conversion passes and the one that observes completion. A pass is bounded
    // by both the eight-band grant and the soft time cutoff, so the count lies
    // between eight bands per pass and one, and is not a fixed number.
    let bands = 36_usize;
    assert!(
        (5 + bands.div_ceil(QUANTA_PER_PASS) + 1..=5 + bands + 2).contains(&passes),
        "{passes} passes"
    );
    assert_eq!(
        stages,
        vec![
            LoadStage::Waiting,
            LoadStage::Read,
            LoadStage::Header,
            LoadStage::Allocate,
            LoadStage::Decode,
            LoadStage::Complete,
        ]
    );
    assert_eq!(store.image(id).unwrap().rgba(), reference);
    assert_eq!(store.counters().bytes_read, 17_497);
    assert_eq!(store.counters().decode_bands, 36);
    assert_eq!(store.staged_bytes(), 0);
    assert_eq!(store.resident_bytes(), reference.len());
}

#[test]
fn admitted_jobs_run_one_at_a_time_in_admission_order() {
    let root = bundle();
    for index in 0..JOB_QUEUE_LIMIT {
        install(root.path(), "interlaced", &format!("art/{index}.png"));
    }
    let mut store = store(root.path());
    let ids: Vec<_> = (0..JOB_QUEUE_LIMIT)
        .map(|index| store.request_png(&format!("art/{index}.png")).unwrap())
        .collect();

    let mut completed = Vec::new();
    let mut passes = 0;
    while completed.len() < ids.len() {
        store.advance(WATCHDOG);
        passes += 1;
        assert!(passes < 500, "queue did not drain");
        // Exactly one job may hold worker resources at a time.
        let loading = ids
            .iter()
            .filter(|id| {
                store
                    .status(**id)
                    .is_some_and(|status| status.state == ImageState::Loading)
            })
            .count();
        assert!(loading <= 1, "{loading} jobs were active at once");
        completed.extend(
            store
                .take_settled()
                .into_iter()
                .map(|status| (status.id, status.state)),
        );
    }
    assert_eq!(
        completed,
        ids.iter()
            .map(|id| (*id, ImageState::Ready))
            .collect::<Vec<_>>()
    );
    assert_eq!(store.pending_jobs(), 0);
}

// ---- eviction, cancellation and teardown -------------------------------

#[test]
fn unload_invalidates_every_alias_and_reports_true_exactly_once() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    let id = store.request_png("art/tiles.png").unwrap();
    let alias = store.request_png("art/tiles.png").unwrap();
    assert_eq!(id, alias);
    assert!(store.drain(WATCHDOG));
    store.take_settled();

    assert!(store.unload(id));
    assert!(!store.unload(alias));
    let status = store.status(id).unwrap();
    assert_eq!(status.state, ImageState::Unloaded);
    assert_eq!(store.size(id), None);
    assert!(store.image(id).is_none());
    let settled = store.take_settled();
    assert_eq!(settled.len(), 1);
    assert_eq!(settled[0].state, ImageState::Unloaded);
    // The terminal entry left the registry with its transition.
    assert!(store.status(id).is_none());
    assert!(!store.unload(id));

    // A later request is a fresh logical image, not a resurrection.
    let reloaded = store.request_png("art/tiles.png").unwrap();
    assert_ne!(reloaded, id);
    assert!(store.drain(WATCHDOG));
    assert_eq!(store.image(reloaded).unwrap().rgba(), expected("rgba"));
}

#[test]
fn unloaded_pixels_stay_pinned_until_their_owner_releases_them() {
    let root = bundle();
    install(root.path(), "interlaced", "art/tiles.png");
    let mut store = store(root.path());
    let id = store.request_png("art/tiles.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let pinned = store.image(id).unwrap();
    let bytes = pinned.rgba().len();
    assert_eq!(store.resident_bytes(), bytes);

    assert!(store.unload(id));
    store.service();
    // A logical unload alone does not make pinned bytes free.
    assert_eq!(store.resident_bytes(), bytes);
    assert_eq!(pinned.rgba(), expected("interlaced"));
    drop(pinned);
    store.service();
    assert_eq!(store.resident_bytes(), 0);
}

#[test]
fn cancelling_at_any_stage_releases_work_without_publishing() {
    let root = bundle();
    fs::copy(kenney(), root.path().join("sheet.png")).unwrap();
    let mut cancelled_while_loading = 0;
    for passes in 0..10 {
        let mut store = store(root.path());
        let id = store.request_png("sheet.png").unwrap();
        for _ in 0..passes {
            store.advance(WATCHDOG);
        }
        let before = store.status(id).unwrap();
        assert!(store.unload(id), "passes={passes}");
        assert!(store.drain(WATCHDOG), "passes={passes}");

        if before.state != ImageState::Ready {
            cancelled_while_loading += 1;
            // No late worker result may publish a cancelled image.
            assert_eq!(store.counters().completed, 0, "passes={passes}");
        }
        assert!(store.image(id).is_none(), "passes={passes}");
        assert_eq!(
            store.status(id).unwrap().state,
            ImageState::Unloaded,
            "passes={passes}"
        );
        assert_eq!(store.pending_jobs(), 0, "passes={passes}");
        assert_eq!(store.staged_bytes(), 0, "passes={passes}");
        assert_eq!(store.scratch_bytes(), 0, "passes={passes}");
        assert_eq!(store.resident_bytes(), 0, "passes={passes}");
        assert!(store.service_fault().is_none(), "passes={passes}");
    }
    assert!(
        cancelled_while_loading >= 5,
        "cancellation never raced an unfinished job"
    );
}

#[test]
fn a_cancelled_queued_job_never_reaches_the_worker() {
    let root = bundle();
    for index in 0..3 {
        install(root.path(), "rgba", &format!("art/{index}.png"));
    }
    let mut store = store(root.path());
    let ids: Vec<_> = (0..3)
        .map(|index| store.request_png(&format!("art/{index}.png")).unwrap())
        .collect();
    assert!(store.unload(ids[1]));
    assert_eq!(store.pending_jobs(), 2);
    assert!(store.drain(WATCHDOG));

    let states: Vec<_> = ids
        .iter()
        .map(|id| store.status(*id).unwrap().state)
        .collect();
    assert_eq!(
        states,
        vec![ImageState::Ready, ImageState::Unloaded, ImageState::Ready]
    );
    assert_eq!(store.counters().completed, 2);
}

#[test]
fn shutdown_cancels_outstanding_work_and_joins_the_worker() {
    let root = bundle();
    fs::copy(kenney(), root.path().join("sheet.png")).unwrap();
    install(root.path(), "rgba", "small.png");
    let mut store = store(root.path());
    let ready = store.request_png("small.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let pinned = store.image(ready).unwrap();
    let loading = store.request_png("sheet.png").unwrap();
    store.advance(WATCHDOG);
    store.advance(WATCHDOG);

    let started = Instant::now();
    store.shutdown();
    assert!(started.elapsed() < WATCHDOG, "worker join stalled");
    assert!(store.status(ready).is_none());
    assert!(store.status(loading).is_none());
    assert_eq!(store.pending_jobs(), 0);
    assert_eq!(store.staged_bytes(), 0);
    // The retained owner still holds valid pixels after the session ends.
    assert_eq!(pinned.rgba(), expected("rgba"));
    assert_eq!(store.resident_bytes(), pinned.rgba().len());
    // Idempotent, and requests are refused afterwards.
    store.shutdown();
    assert_eq!(
        store.request_png("small.png").unwrap_err().code,
        AssetErrorCode::Path
    );
    drop(pinned);
}

/// Tearing a store down mid-load must release what the cancelled job reserved.
/// Retained storage is shared with published and pinned content, so no blanket
/// reset can do this; only the job's own bytes may be dropped.
#[test]
fn shutdown_releases_the_reservations_of_a_cancelled_job() {
    let root = bundle();
    fs::copy(kenney(), root.path().join("sheet.png")).unwrap();
    let mut interrupted_after_reserving = 0;
    for passes in 0..12 {
        let mut store = store(root.path());
        let id = store.request_png("sheet.png").unwrap();
        for _ in 0..passes {
            store.advance(WATCHDOG);
        }
        if store.status(id).unwrap().state != ImageState::Ready && store.resident_bytes() > 0 {
            interrupted_after_reserving += 1;
        }
        store.shutdown();
        // Nothing published and nothing pinned, so every counter returns to zero.
        assert_eq!(store.resident_bytes(), 0, "passes={passes}");
        assert_eq!(store.staged_bytes(), 0, "passes={passes}");
        assert_eq!(store.scratch_bytes(), 0, "passes={passes}");
    }
    // The output reservation is taken a pass before the image can be published,
    // so a run that never observed it would prove nothing.
    assert!(
        interrupted_after_reserving > 0,
        "no shutdown interrupted a job that had already reserved its output"
    );
}

#[test]
fn dropping_a_store_mid_load_terminates_its_worker() {
    let root = bundle();
    fs::copy(kenney(), root.path().join("sheet.png")).unwrap();
    let started = Instant::now();
    for _ in 0..8 {
        let mut store = store(root.path());
        store.request_png("sheet.png").unwrap();
        store.advance(WATCHDOG);
        drop(store);
    }
    assert!(started.elapsed() < WATCHDOG, "worker teardown stalled");
}

// ---- large fixtures ----------------------------------------------------

/// Build the incompressible maximum-size fixture once per test that needs it.
/// Roughly 16.8 MB on disk and 16 MiB of decoded output.
fn maximum_image() -> (Vec<u8>, Vec<u8>) {
    let size = DIMENSION_LIMIT as usize;
    let pixels = png::noise(size, size);
    let encoded = png::rgba(&pixels, size, size);
    (pixels, encoded)
}

#[test]
fn the_encoded_cap_admits_exactly_seventeen_mebibytes_and_probes_one_further_byte() {
    let root = bundle();
    let (pixels, encoded) = maximum_image();
    assert_eq!(pixels.len(), IMAGE_RGBA_LIMIT);
    // The encoded form of a maximum image can exceed its decoded size, which
    // is exactly why the encoded cap carries headroom above 16 MiB.
    assert!(
        encoded.len() > IMAGE_RGBA_LIMIT && encoded.len() < ENCODED_IMAGE_LIMIT,
        "encoded {} bytes",
        encoded.len()
    );
    // Stated exactly so the recorded headroom figure stays checkable: 2048 rows
    // of a filter byte and 8192 pixel bytes, in 257 stored DEFLATE blocks, plus
    // zlib and chunk framing. Phase 0's independently encoded fixture reached
    // the same size, since incompressible input also lands in stored blocks.
    assert_eq!(encoded.len(), 16_780_612);
    fs::write(root.path().join("large.png"), &encoded).unwrap();

    // Padding after IEND keeps the pixels valid, so exactly the cap still
    // decodes while one more byte is refused.
    let mut at_limit = encoded.clone();
    at_limit.resize(ENCODED_IMAGE_LIMIT, 0);
    fs::write(root.path().join("at-limit.png"), &at_limit).unwrap();
    at_limit.push(0);
    fs::write(root.path().join("over-limit.png"), &at_limit).unwrap();

    let mut store = store(root.path());
    assert_eq!(load(&mut store, "large.png"), pixels);
    assert_eq!(store.counters().bytes_read, encoded.len() as u64);

    let before = store.counters();
    let at = store.request_png("at-limit.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let status = store.status(at).unwrap();
    assert_eq!(status.state, ImageState::Ready);
    // Exactly the cap was read and accepted, so the bound is decided by the
    // bytes that actually arrived rather than by the metadata alone.
    assert_eq!(status.bytes_read, ENCODED_IMAGE_LIMIT);
    assert_eq!(store.image(at).unwrap().rgba(), pixels);
    let calls = store.counters().read_calls - before.read_calls;
    // 544 whole quanta, then at least the one-byte overflow probe at EOF.
    assert!(
        calls >= (ENCODED_IMAGE_LIMIT / WORK_QUANTUM + 1) as u64,
        "{calls} read calls"
    );

    let before = store.counters();
    let over = store.request_png("over-limit.png").unwrap();
    assert!(store.drain(WATCHDOG));
    let status = store.status(over).unwrap();
    assert_eq!(status.state, ImageState::Failed);
    assert_eq!(status.error.unwrap().code, AssetErrorCode::Limit);
    // Refused from the early metadata check, before any content was read.
    assert_eq!(store.counters().read_calls, before.read_calls);
    assert_eq!(store.staged_bytes(), 0);
}

/// The early metadata refusal cannot prove that the cap is decided by bytes
/// that actually arrived, because it rejects an oversized file before the first
/// read. Growing the file after its metadata has already been accepted is the
/// only way the read-based check and its one-byte overflow probe can fire, and
/// it is the case that check exists for.
#[test]
fn a_file_that_grows_after_its_metadata_check_is_refused_by_the_reads() {
    let root = bundle();
    let (_, encoded) = maximum_image();
    let mut at_limit = encoded;
    at_limit.resize(ENCODED_IMAGE_LIMIT, 0);
    let path = root.path().join("growing.png");
    fs::write(&path, &at_limit).unwrap();

    let mut store = store(root.path());
    let id = store.request_png("growing.png").unwrap();
    // Two passes open the file and dispatch its first read grant, so the
    // worker's metadata check has already accepted exactly the cap. Only a
    // quantum of a 17 MiB file has been read, so the appended byte lands far
    // ahead of the reader.
    store.advance(WATCHDOG);
    store.advance(WATCHDOG);
    assert_eq!(store.status(id).unwrap().state, ImageState::Loading);
    fs::OpenOptions::new()
        .append(true)
        .open(&path)
        .unwrap()
        .write_all(&[0])
        .unwrap();

    assert!(store.drain(WATCHDOG));
    let status = store.status(id).unwrap();
    assert_eq!(status.state, ImageState::Failed);
    assert_eq!(status.error.unwrap().code, AssetErrorCode::Limit);
    // The probe read exactly one byte past the cap and refused there, rather
    // than reading whatever else the file had grown to hold.
    assert_eq!(status.bytes_read, ENCODED_IMAGE_LIMIT + 1);
    assert_eq!(store.staged_bytes(), 0);
    assert_eq!(store.resident_bytes(), 0);
    assert!(store.service_fault().is_none());
}

#[test]
fn two_maximum_files_load_within_the_aggregate_staging_allowance() {
    let root = bundle();
    let (pixels, encoded) = maximum_image();
    fs::write(root.path().join("a.png"), &encoded).unwrap();
    fs::write(root.path().join("b.png"), &encoded).unwrap();
    assert!(encoded.len() * 2 < ENCODED_STAGING_LIMIT);

    let mut store = store(root.path());
    let a = store.request_png("a.png").unwrap();
    let b = store.request_png("b.png").unwrap();
    // Distinct files with identical bytes are distinct images.
    assert_ne!(a, b);

    let mut peak = 0;
    let mut passes = 0;
    while store.pending_jobs() > 0 {
        store.advance(WATCHDOG);
        passes += 1;
        assert!(passes < 5_000, "aggregate load did not converge");
        peak = peak.max(store.staged_bytes());
        assert!(store.staged_bytes() <= ENCODED_STAGING_LIMIT);
    }
    assert_eq!(store.image(a).unwrap().rgba(), pixels);
    assert_eq!(store.image(b).unwrap().rgba(), pixels);
    assert_eq!(store.resident_bytes(), 2 * IMAGE_RGBA_LIMIT);
    // One job reads at a time, so staging peaks near a single encoded file.
    assert!(
        peak <= ENCODED_IMAGE_LIMIT + QUANTA_PER_PASS * WORK_QUANTUM,
        "peak staging {peak}"
    );
    assert_eq!(store.staged_bytes(), 0);
}

#[test]
fn retained_storage_pressure_fails_a_job_as_capacity() {
    let root = bundle();
    let (_, encoded) = maximum_image();
    let count = STORE_RGBA_LIMIT / IMAGE_RGBA_LIMIT;
    fs::write(root.path().join("0.png"), &encoded).unwrap();
    for index in 1..=count {
        fs::copy(
            root.path().join("0.png"),
            root.path().join(format!("{index}.png")),
        )
        .unwrap();
    }

    let mut store = store(root.path());
    for index in 0..count {
        let id = store.request_png(&format!("{index}.png")).unwrap();
        assert!(store.drain(WATCHDOG));
        assert_eq!(
            store.status(id).unwrap().state,
            ImageState::Ready,
            "image {index}"
        );
    }
    assert_eq!(store.resident_bytes(), STORE_RGBA_LIMIT);

    // The store is full: the next job fails as capacity rather than stalling.
    let refused = store.request_png(&format!("{count}.png")).unwrap();
    assert!(store.drain(WATCHDOG));
    let status = store.status(refused).unwrap();
    assert_eq!(status.state, ImageState::Failed);
    assert_eq!(status.error.unwrap().code, AssetErrorCode::Capacity);
    // Its dimensions were validated before allocation was refused.
    assert_eq!(
        (status.width, status.height),
        (Some(DIMENSION_LIMIT), Some(DIMENSION_LIMIT))
    );
    assert_eq!(store.resident_bytes(), STORE_RGBA_LIMIT);
    assert!(store.service_fault().is_none());

    // Releasing one image makes room for the retry.
    let first = store.take_settled()[0].id;
    assert!(store.unload(first));
    store.service();
    assert_eq!(store.resident_bytes(), STORE_RGBA_LIMIT - IMAGE_RGBA_LIMIT);
    let retry = store.request_png(&format!("{count}.png")).unwrap();
    assert!(store.drain(WATCHDOG));
    assert_eq!(store.status(retry).unwrap().state, ImageState::Ready);
}

// ---- status snapshots --------------------------------------------------

#[test]
fn status_snapshots_are_owned_and_survive_later_service_passes() {
    let root = bundle();
    install(root.path(), "rgba", "art/tiles.png");
    let mut store = store(root.path());
    let id = store.request_png("art/tiles.png").unwrap();
    let queued: ImageStatus = store.status(id).unwrap();
    assert_eq!(queued.state, ImageState::Queued);
    assert_eq!(queued.stage, LoadStage::Waiting);
    assert_eq!(queued.bytes_read, 0);
    assert_eq!(queued.width, None);

    assert!(store.drain(WATCHDOG));
    // The earlier snapshot is a copy, not a view onto the store.
    assert_eq!(queued.state, ImageState::Queued);
    assert_eq!(store.status(id).unwrap().state, ImageState::Ready);
    let retained: ImageId = queued.id;
    assert!(store.status(retained).is_some());
}

// ---- process-bounded decoder probes -------------------------------------

/// Decoder work runs to completion inside non-preemptible stages, and a store
/// joins its worker on drop, so neither `drain`'s deadline nor an unwinding
/// assertion can bound a decoder that never returns. Run the adversarial
/// fixtures in child processes, as `scripting_feasibility` does for the VM, so a
/// regression fails in ten seconds instead of hanging Cargo. The in-process
/// tests above keep their own assertions; what these add is the outer bound.
#[test]
fn adversarial_decoder_fixtures_stay_inside_a_process_watchdog() {
    for probe in [
        "truncated",
        "corrupt",
        "wrong_format",
        "sixteen_bit",
        "apng",
        "huge_dimensions",
        "interlaced",
        "maximum",
        "maximum_drop",
    ] {
        let mut child = Command::new(std::env::current_exe().unwrap())
            .args(["--exact", "isolated_probe", "--nocapture"])
            .env("PROTOGINE_ASSET_PROBE", probe)
            .stdout(std::process::Stdio::null())
            .spawn()
            .unwrap();
        let deadline = Instant::now() + WATCHDOG;
        loop {
            if let Some(status) = child.try_wait().unwrap() {
                assert!(status.success(), "{probe}: {status}");
                break;
            }
            if Instant::now() >= deadline {
                child.kill().unwrap();
                child.wait().unwrap();
                panic!("{probe} exceeded the 10-second process timeout");
            }
            thread::sleep(Duration::from_millis(10));
        }
    }
}

#[test]
fn isolated_probe() {
    let Ok(probe) = std::env::var("PROTOGINE_ASSET_PROBE") else {
        return;
    };
    let root = bundle();
    // The two full decodes are here because of the stages they run, not because
    // their pixels need rechecking: the eagerly decoded Adam7 frame, and a
    // maximum image whose allocation and conversion are the largest this
    // milestone accepts. The rest are refusals reached through the decoder.
    let refusal = match probe.as_str() {
        "truncated" | "corrupt" | "wrong_format" => Some(AssetErrorCode::Format),
        "sixteen_bit" | "apng" => Some(AssetErrorCode::Unsupported),
        "huge_dimensions" => Some(AssetErrorCode::Limit),
        "interlaced" => None,
        "maximum" | "maximum_drop" => {
            let (pixels, encoded) = maximum_image();
            fs::write(root.path().join("art.png"), &encoded).unwrap();
            let mut store = store(root.path());
            let id = store.request_png("art.png").unwrap();
            if probe == "maximum_drop" {
                // Tear the store down while the worker still holds the file,
                // the decoder and its buffers. The join is unconditional, so
                // only this watchdog bounds it.
                store.advance(WATCHDOG);
                store.advance(WATCHDOG);
                drop(store);
                return;
            }
            assert!(store.drain(WATCHDOG), "{probe} did not settle");
            assert_eq!(store.image(id).unwrap().rgba(), pixels, "{probe}");
            return;
        }
        other => panic!("unknown asset probe: {other}"),
    };
    install(root.path(), &probe, "art.png");
    let mut store = store(root.path());
    let id = store.request_png("art.png").unwrap();
    assert!(store.drain(WATCHDOG), "{probe} did not settle");
    let status = store.status(id).unwrap();
    match refusal {
        Some(code) => {
            assert_eq!(status.state, ImageState::Failed, "{probe}");
            assert_eq!(status.error.unwrap().code, code, "{probe}");
        }
        None => {
            assert_eq!(status.state, ImageState::Ready, "{probe}");
            assert_eq!(store.image(id).unwrap().rgba(), expected(&probe), "{probe}");
        }
    }
    assert!(store.service_fault().is_none(), "{probe}");
}
