/* ABI v1: x86_64-pc-windows-msvc, default C alignment/calling convention.
 * Trusted native code only. No exceptions, retained host buffers or background
 * callbacks. Exact table sizes/version are required; no implicit extensions.
 */
#if defined(_WIN32)
#define PG_PLUGIN_EXPORT __declspec(dllexport)
#else
#define PG_PLUGIN_EXPORT
#endif


#ifndef PROTOGINE_PLUGIN_H
#define PROTOGINE_PLUGIN_H

/* Generated by cbindgen 0.29.2 from sdk/src/lib.rs. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define PG_ABI_VERSION 1

#define PG_OK 0

#define PG_INVALID_ARGUMENT 1

#define PG_UNSUPPORTED 2

#define PG_ERROR 3

#define PG_BUFFER_TOO_SMALL 4

#define PG_PANIC 5

#define PG_CONTRACT_ERROR 6

#define PG_LOG_INFO 0

#define PG_LOG_WARN 1

#define PG_LOG_ERROR 2

#define PG_ERROR_CAPACITY 1024

/**
 * UTF-8 bytes, without a terminator. NULL is permitted only for length zero.
 */
typedef struct PgStr {
  const uint8_t *data;
  uint32_t len;
} PgStr;

typedef uint32_t (*PgLog)(void *context, uint32_t level, struct PgStr message);

/**
 * Valid only during the current host-initiated call on the runtime thread.
 * Do not retain this table, its context, or callback arguments. Reserved = 0.
 */
typedef struct PgHost {
  uint32_t abi_version;
  uint32_t struct_size;
  void *context;
  PgLog log;
  uint64_t reserved[2];
} PgHost;

/**
 * Host-owned read-only byte span. NULL is permitted only for length zero.
 */
typedef struct PgBytes {
  const uint8_t *data;
  uint64_t len;
} PgBytes;

/**
 * Host-owned output. Do not change data/capacity or retain pointers after return.
 * On success, written <= capacity. On failure, written must be zero.
 */
typedef struct PgOutput {
  uint8_t *data;
  uint64_t capacity;
  uint64_t written;
} PgOutput;

/**
 * Host-owned diagnostic storage. Only written and data[0..capacity] may change.
 * written excludes any terminator and must be <= capacity, including on failure.
 */
typedef struct PgError {
  uint8_t *data;
  uint32_t capacity;
  uint32_t written;
} PgError;

/**
 * Synchronous batch computation. Join all workers before return. Inputs and
 * output/error buffers are disjoint and host-owned. Errors must leave instance
 * state unchanged; panic/contract faults discard the session. Never reenter Lua.
 * No automatic retry occurs. Byte encodings belong to the declared schema.
 */
typedef uint32_t (*PgCall)(const struct PgHost *host,
                           void *instance,
                           struct PgBytes input,
                           struct PgOutput *output,
                           struct PgError *error);

/**
 * Immutable declaration stored in the library until unload. IDs and schema IDs
 * are dotted lowercase identifiers; schema_version is nonzero. Reserved = 0.
 */
typedef struct PgFunction {
  uint32_t struct_size;
  uint32_t schema_version;
  struct PgStr id;
  struct PgStr schema;
  PgCall call;
  uint64_t reserved[2];
} PgFunction;

/**
 * Successful init publishes a non-NULL plugin-owned instance. Failed init must
 * clean up its allocations and leave *instance NULL. No exception may unwind.
 */
typedef uint32_t (*PgInit)(const struct PgHost *host, void **instance, struct PgError *error);

/**
 * Always consumes/frees the instance, even when reporting failure. Called once.
 */
typedef uint32_t (*PgShutdown)(const struct PgHost *host, void *instance, struct PgError *error);

/**
 * Query copies this exact v1 layout into host storage. All function pointers
 * are required. functions is NULL iff function_count == 0. Flags/reserved = 0.
 * Query must not create an instance. Every declaration is validated before init.
 * ID/function storage must be readable, correctly aligned and immutable until
 * library unload; function_count must describe the actual accessible array.
 */
typedef struct PgPlugin {
  uint32_t abi_version;
  uint32_t struct_size;
  struct PgStr id;
  const struct PgFunction *functions;
  uint32_t function_count;
  uint32_t flags;
  PgInit init;
  PgShutdown shutdown;
  uint64_t reserved[2];
} PgPlugin;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The only required exported symbol. Reject unsupported ABI/size before
 * touching destination. Never write beyond destination_size or unwind.
 */
PG_PLUGIN_EXPORT uint32_t protogine_plugin_query(uint32_t requested_abi,
                                       uint32_t destination_size,
                                       struct PgPlugin *destination,
                                       struct PgError *error);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PROTOGINE_PLUGIN_H */
